version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: portree
    main: .
    binary: portree
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      # TODO: Windows support requires platform-specific process management
      # - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/fairy-pitta/portree/cmd.version={{.Version}}
      - -X github.com/fairy-pitta/portree/cmd.commit={{.Commit}}
      - -X github.com/fairy-pitta/portree/cmd.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

brews:
  - repository:
      owner: fairy-pitta
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/fairy-pitta/portree
    description: Git Worktree Server Manager
    license: MIT
    install: |
      bin.install "portree"
    test: |
      system "#{bin}/portree", "version"

release:
  github:
    owner: fairy-pitta
    name: portree
  draft: false
  prerelease: auto
